<?php
// Bank list for multiple countries worldwide

$banks = [
    'USA' => [
        'Chase Bank',
        'Bank of America',
        'Wells Fargo',
        'Citibank',
        'U.S. Bank',
        'Capital One',
        'TD Bank',
        'Regions Bank',
        'Ally Bank',
        'Charles Schwab Bank',
        'HSBC Bank USA',
        'PNC Bank',
        'Sunwest Bank',
        'Fifth Third Bank',
        'Santander Bank',
        'KeyBank',
        'Truist Bank',
        'Citizens Bank',
        'M&T Bank',
        'BMO Harris Bank',
        'Comerica',
        'Cullen/Frost Bankers',
        'New York Community Bank',
        'Flagstar Bank',
        'EB Financial Bank',
        'Amalgamated Bank',
        'Umpqua Bank',
        'Zions Bancorporation',
        'Western Alliance Bank',
        'Synchrony Bank',
        'American Express Bank',
    ],
    'Korea' => [
        'KB Kookmin Bank',
        'Shinhan Bank',
        'Samsung Electronics Bank',
        'Hyundai Bank',
        'Woori Bank',
        'Hana Bank',
        'IBK (Industrial Bank of Korea)',
        'NH Nonghyup Bank',
        'Citibank Korea',
        'DGB Financial Group',
        'BNK Busan Bank',
        'Jeju Bank',
        'Gwangju Bank',
        'Daegu Bank',
        'Bank of Seoul',
        'SCB (Standard Chartered Bank Korea)',
        'HSBC Bank Korea',
        'JP Morgan Chase Bank Korea',
        'Goldman Sachs Korea',
        'Morgan Stanley Bank Korea',
    ],
    'Taiwan' => [
        'Taiwan Cooperative Bank',
        'Bank of Taiwan',
        'First Commercial Bank',
        'Hua Nan Commercial Bank',
        'Cathay United Bank',
        'Mega International Commercial Bank',
        'China Commercial Bank',
        'Chang Hwa Commercial Bank',
        'Shanghai Commercial and Savings Bank',
        'Taipei Fubon Commercial Bank',
        'Bank of Kaohsiung',
        'Taichung Commercial Bank',
        'Taishin International Bank',
        'Chinatrust Commercial Bank',
        'E.SUN Commercial Bank',
        'Standard Chartered Bank Taiwan',
        'Citibank Taiwan',
        'HSBC Bank Taiwan',
        'Bank of America Taiwan',
        'Mizuho Bank Taiwan',
        'DBS Bank Taiwan',
        'United Overseas Bank Taiwan',
    ],
    'Mexico' => [
        'Banco Azteca',
        'Banco Autofin Mexico',
        'Banco Compartamos',
        'Banco Finterra',
        'Banco Inbursa',
        'Banco Invex',
        'Banco Mifel',
        'Banco Multiva',
        'Banco Ve Por Mas',
        'Bankaool',
        'BBVA Mexico',
        'Scotiabank Inverlat',
        'Santander Mexico',
        'HSBC Mexico',
        'Citibanamex',
        'American Express Bank Mexico',
        'Barclays Bank Mexico',
        'JP Morgan Chase Bank Mexico',
        'Banco Afirme',
        'Consubanco',
        'Intercam Banco',
        'Nafin (Nacional Financiera)',
        'Banco Regional de Monterrey',
        'Banco Sabadell',
    ],
    'UK' => [
        'HSBC UK',
        'Barclays',
        'Lloyds Bank',
        'NatWest',
        'Santander UK',
        'Royal Bank of Scotland',
        'TSB Bank',
        'Halifax',
        'Metro Bank',
        'Nationwide Building Society',
        'Standard Chartered UK',
        'Virgin Money',
        'Monzo',
        'Revolut',
        'Starling Bank',
        'First Direct',
        'The Co-operative Bank',
        'Yorkshire Bank',
        'Clydesdale Bank',
    ],
    'Canada' => [
        'Royal Bank of Canada (RBC)',
        'Toronto-Dominion Bank (TD)',
        'Bank of Nova Scotia (Scotiabank)',
        'Bank of Montreal (BMO)',
        'Canadian Imperial Bank of Commerce (CIBC)',
        'National Bank of Canada',
        'Desjardins Group',
        'HSBC Canada',
        'Laurentian Bank',
        'Canadian Western Bank',
        'Tangerine Bank',
        'Simplii Financial',
        'EQ Bank',
        'Manulife Bank',
        'Vancity',
        'ATB Financial',
    ],
    'India' => [
        'State Bank of India (SBI)',
        'HDFC Bank',
        'ICICI Bank',
        'Punjab National Bank (PNB)',
        'Bank of Baroda',
        'Axis Bank',
        'Canara Bank',
        'Bank of India',
        'Union Bank of India',
        'Indian Bank',
        'Central Bank of India',
        'Kotak Mahindra Bank',
        'IndusInd Bank',
        'Yes Bank',
        'IDBI Bank',
        'Federal Bank',
        'Bandhan Bank',
        'IDFC First Bank',
        'RBL Bank',
        'South Indian Bank',
    ],
    'Nigeria' => [
        'First Bank of Nigeria',
        'United Bank for Africa (UBA)',
        'Zenith Bank',
        'Access Bank',
        'Guaranty Trust Bank (GTBank)',
        'Ecobank Nigeria',
        'Fidelity Bank',
        'Union Bank of Nigeria',
        'Sterling Bank',
        'Stanbic IBTC Bank',
        'Wema Bank',
        'Unity Bank',
        'Polaris Bank',
        'Keystone Bank',
        'Heritage Bank',
        'Providus Bank',
        'Jaiz Bank',
        'Kuda Bank',
        'Opay',
        'PalmPay',
    ],
    'Japan' => [
        'Mitsubishi UFJ Financial Group',
        'Sumitomo Mitsui Banking Corporation',
        'Mizuho Financial Group',
        'Japan Post Bank',
        'Resona Holdings',
        'Shinsei Bank',
        'Aozora Bank',
        'Nomura Holdings',
        'Daiwa Securities Group',
        'SBI Sumishin Net Bank',
        'Rakuten Bank',
        'Sony Bank',
        'Seven Bank',
        'Jibun Bank',
        'PayPay Bank',
    ],
    'Germany' => [
        'Deutsche Bank',
        'Commerzbank',
        'KfW',
        'DZ Bank',
        'Landesbank Baden-Württemberg',
        'Norddeutsche Landesbank',
        'Bayerische Landesbank',
        'Helaba',
        'NRW.Bank',
        'ING-DiBa',
        'Postbank',
        'Santander Consumer Bank',
        'Targobank',
        'Comdirect Bank',
        'N26',
        'Revolut Germany',
    ],
    'Australia' => [
        'Commonwealth Bank',
        'Westpac',
        'ANZ',
        'National Australia Bank (NAB)',
        'Macquarie Bank',
        'Bendigo Bank',
        'Bank of Queensland',
        'Suncorp Bank',
        'ING Australia',
        'AMP Bank',
        'HSBC Australia',
    ],
    'France' => [
        'BNP Paribas',
        'Crédit Agricole',
        'Société Générale',
        'Groupe BPCE',
        'Crédit Mutuel',
        'La Banque Postale',
        'CIC',
        'Caisse d\'Épargne',
        'Banque Populaire',
        'LCL',
        'HSBC France',
        'Boursorama',
        'Hello Bank',
        'N26 France',
    ]
];

// Return as JSON for API
if ($_SERVER['REQUEST_METHOD'] === 'GET' && isset($_GET['api'])) {
    header('Content-Type: application/json');
    echo json_encode($banks);
    exit;
}

// Return for PHP usage
return $banks;
?>
